"""initial schema

Revision ID: ff957f57f077
Revises: 
Create Date: 2026-07-31 18:31:08.774727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.core.crypto


revision: str = 'ff957f57f077'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abteilung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('handlungsfeld',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abteilung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abteilung_id'], ['abteilung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handlungsfeld_abteilung_id'), 'handlungsfeld', ['abteilung_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('teilnehmer', 'berufstrainer', 'psychosoziale_mitarbeit', 'einrichtungs_admin', name='roleenum'), nullable=False),
    sa.Column('abteilung_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['abteilung_id'], ['abteilung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('auditlogeintrag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zeitpunkt', sa.DateTime(), nullable=False),
    sa.Column('akteur_id', sa.Integer(), nullable=False),
    sa.Column('aktion', sa.Enum('wohlbefinden_gelesen', 'bewerbung_gelesen', name='auditaktion'), nullable=False),
    sa.Column('zieltyp', sa.Enum('wohlbefinden', 'bewerbung', name='auditzieltyp'), nullable=False),
    sa.Column('ziel_teilnehmer_id', sa.Integer(), nullable=False),
    sa.Column('grundlage_freigabe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['akteur_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlogeintrag_akteur_id'), 'auditlogeintrag', ['akteur_id'], unique=False)
    op.create_index(op.f('ix_auditlogeintrag_ziel_teilnehmer_id'), 'auditlogeintrag', ['ziel_teilnehmer_id'], unique=False)
    op.create_table('berufstrainerzuordnung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('berufstrainer_id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['berufstrainer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_berufstrainerzuordnung_berufstrainer_id'), 'berufstrainerzuordnung', ['berufstrainer_id'], unique=False)
    op.create_index(op.f('ix_berufstrainerzuordnung_teilnehmer_id'), 'berufstrainerzuordnung', ['teilnehmer_id'], unique=False)
    op.create_table('bewerbung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.Column('firma', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('entwurf', 'versendet', 'rueckmeldung_offen', 'eingeladen', 'abgesagt', 'zugesagt', name='bewerbungstatus'), nullable=False),
    sa.Column('beworben_am', sa.Date(), nullable=True),
    sa.Column('naechster_termin', sa.Date(), nullable=True),
    sa.Column('notizen', app.core.crypto.VerschluesselterText(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bewerbung_teilnehmer_id'), 'bewerbung', ['teilnehmer_id'], unique=False)
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('typ', sa.Enum('team', 'person', name='boardtyp'), nullable=False),
    sa.Column('handlungsfeld_id', sa.Integer(), nullable=True),
    sa.Column('person_teilnehmer_id', sa.Integer(), nullable=True),
    sa.Column('ersteller_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ersteller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['handlungsfeld_id'], ['handlungsfeld.id'], ),
    sa.ForeignKeyConstraint(['person_teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_handlungsfeld_id'), 'board', ['handlungsfeld_id'], unique=False)
    op.create_index(op.f('ix_board_person_teilnehmer_id'), 'board', ['person_teilnehmer_id'], unique=False)
    op.create_table('handlungsfeldleitung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handlungsfeld_id', sa.Integer(), nullable=False),
    sa.Column('berufstrainer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['berufstrainer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['handlungsfeld_id'], ['handlungsfeld.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handlungsfeldleitung_berufstrainer_id'), 'handlungsfeldleitung', ['berufstrainer_id'], unique=False)
    op.create_index(op.f('ix_handlungsfeldleitung_handlungsfeld_id'), 'handlungsfeldleitung', ['handlungsfeld_id'], unique=False)
    op.create_table('handlungsfeldmitglied',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handlungsfeld_id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.Column('hinzugefuegt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handlungsfeld_id'], ['handlungsfeld.id'], ),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handlungsfeldmitglied_handlungsfeld_id'), 'handlungsfeldmitglied', ['handlungsfeld_id'], unique=False)
    op.create_index(op.f('ix_handlungsfeldmitglied_teilnehmer_id'), 'handlungsfeldmitglied', ['teilnehmer_id'], unique=False)
    op.create_table('psmzuordnung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psm_id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['psm_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psmzuordnung_psm_id'), 'psmzuordnung', ['psm_id'], unique=False)
    op.create_index(op.f('ix_psmzuordnung_teilnehmer_id'), 'psmzuordnung', ['teilnehmer_id'], unique=False)
    op.create_table('teilnehmergruppe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('handlungsfeld_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_von', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['erstellt_von'], ['user.id'], ),
    sa.ForeignKeyConstraint(['handlungsfeld_id'], ['handlungsfeld.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teilnehmergruppe_handlungsfeld_id'), 'teilnehmergruppe', ['handlungsfeld_id'], unique=False)
    op.create_table('wochenbericht',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.Column('kw_jahr', sa.Integer(), nullable=False),
    sa.Column('kw_nummer', sa.Integer(), nullable=False),
    sa.Column('tage', sa.JSON(), nullable=True),
    sa.Column('besonderheiten', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('entwurf', 'abgegeben', name='wochenberichtstatus'), nullable=False),
    sa.Column('abgegeben_am', sa.DateTime(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wochenbericht_teilnehmer_id'), 'wochenbericht', ['teilnehmer_id'], unique=False)
    op.create_table('wohlbefindeneintrag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('stimmung', sa.Float(), nullable=False),
    sa.Column('belastbarkeit', sa.Float(), nullable=False),
    sa.Column('kommentar', app.core.crypto.VerschluesselterText(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teilnehmer_id', 'datum')
    )
    op.create_index(op.f('ix_wohlbefindeneintrag_datum'), 'wohlbefindeneintrag', ['datum'], unique=False)
    op.create_index(op.f('ix_wohlbefindeneintrag_teilnehmer_id'), 'wohlbefindeneintrag', ['teilnehmer_id'], unique=False)
    op.create_table('wohlbefindenfreigabe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.Column('empfaenger_id', sa.Integer(), nullable=False),
    sa.Column('umfang', sa.Enum('alle', 'zeitraum', name='wohlbefindenfreigabeumfang'), nullable=False),
    sa.Column('gueltig_bis', sa.Date(), nullable=True),
    sa.Column('widerrufen_am', sa.DateTime(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empfaenger_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wohlbefindenfreigabe_empfaenger_id'), 'wohlbefindenfreigabe', ['empfaenger_id'], unique=False)
    op.create_index(op.f('ix_wohlbefindenfreigabe_teilnehmer_id'), 'wohlbefindenfreigabe', ['teilnehmer_id'], unique=False)
    op.create_table('bewerbungsfreigabe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.Column('empfaenger_id', sa.Integer(), nullable=False),
    sa.Column('umfang', sa.Enum('alle', 'einzeln', name='bewerbungsfreigabeumfang'), nullable=False),
    sa.Column('bewerbung_id', sa.Integer(), nullable=True),
    sa.Column('gueltig_bis', sa.Date(), nullable=True),
    sa.Column('widerrufen_am', sa.DateTime(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bewerbung_id'], ['bewerbung.id'], ),
    sa.ForeignKeyConstraint(['empfaenger_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bewerbungsfreigabe_bewerbung_id'), 'bewerbungsfreigabe', ['bewerbung_id'], unique=False)
    op.create_index(op.f('ix_bewerbungsfreigabe_empfaenger_id'), 'bewerbungsfreigabe', ['empfaenger_id'], unique=False)
    op.create_index(op.f('ix_bewerbungsfreigabe_teilnehmer_id'), 'bewerbungsfreigabe', ['teilnehmer_id'], unique=False)
    op.create_table('bewerbungsunterlage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.Column('kategorie', sa.Enum('lebenslauf', 'zeugnis', 'anschreiben', 'deckblatt', name='unterlagenkategorie'), nullable=False),
    sa.Column('bewerbung_id', sa.Integer(), nullable=True),
    sa.Column('original_dateiname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speicherpfad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('groesse_bytes', sa.Integer(), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('hochgeladen_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bewerbung_id'], ['bewerbung.id'], ),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bewerbungsunterlage_bewerbung_id'), 'bewerbungsunterlage', ['bewerbung_id'], unique=False)
    op.create_index(op.f('ix_bewerbungsunterlage_teilnehmer_id'), 'bewerbungsunterlage', ['teilnehmer_id'], unique=False)
    op.create_table('boardfreigabe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('gruppe_id', sa.Integer(), nullable=False),
    sa.Column('freigegeben_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['gruppe_id'], ['teilnehmergruppe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boardfreigabe_board_id'), 'boardfreigabe', ['board_id'], unique=False)
    op.create_index(op.f('ix_boardfreigabe_gruppe_id'), 'boardfreigabe', ['gruppe_id'], unique=False)
    op.create_table('spalte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teilnehmergruppemitglied',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gruppe_id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gruppe_id'], ['teilnehmergruppe.id'], ),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teilnehmergruppemitglied_gruppe_id'), 'teilnehmergruppemitglied', ['gruppe_id'], unique=False)
    op.create_index(op.f('ix_teilnehmergruppemitglied_teilnehmer_id'), 'teilnehmergruppemitglied', ['teilnehmer_id'], unique=False)
    op.create_table('karte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spalte_id', sa.Integer(), nullable=False),
    sa.Column('titel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('beschreibung', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('faelligkeit', sa.Date(), nullable=True),
    sa.Column('ersteller_id', sa.Integer(), nullable=False),
    sa.Column('sichtbarkeit', sa.Enum('team', 'privat', name='kartensichtbarkeit'), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ersteller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['spalte_id'], ['spalte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kartenzuweisung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('karte_id', sa.Integer(), nullable=False),
    sa.Column('teilnehmer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['karte_id'], ['karte.id'], ),
    sa.ForeignKeyConstraint(['teilnehmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kartenzuweisung_karte_id'), 'kartenzuweisung', ['karte_id'], unique=False)
    op.create_index(op.f('ix_kartenzuweisung_teilnehmer_id'), 'kartenzuweisung', ['teilnehmer_id'], unique=False)
    op.create_table('unteraufgabe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('karte_id', sa.Integer(), nullable=False),
    sa.Column('titel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('erledigt', sa.Boolean(), nullable=False),
    sa.Column('zugewiesen_an', sa.Integer(), nullable=True),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['karte_id'], ['karte.id'], ),
    sa.ForeignKeyConstraint(['zugewiesen_an'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unteraufgabe_karte_id'), 'unteraufgabe', ['karte_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unteraufgabe_karte_id'), table_name='unteraufgabe')
    op.drop_table('unteraufgabe')
    op.drop_index(op.f('ix_kartenzuweisung_teilnehmer_id'), table_name='kartenzuweisung')
    op.drop_index(op.f('ix_kartenzuweisung_karte_id'), table_name='kartenzuweisung')
    op.drop_table('kartenzuweisung')
    op.drop_table('karte')
    op.drop_index(op.f('ix_teilnehmergruppemitglied_teilnehmer_id'), table_name='teilnehmergruppemitglied')
    op.drop_index(op.f('ix_teilnehmergruppemitglied_gruppe_id'), table_name='teilnehmergruppemitglied')
    op.drop_table('teilnehmergruppemitglied')
    op.drop_table('spalte')
    op.drop_index(op.f('ix_boardfreigabe_gruppe_id'), table_name='boardfreigabe')
    op.drop_index(op.f('ix_boardfreigabe_board_id'), table_name='boardfreigabe')
    op.drop_table('boardfreigabe')
    op.drop_index(op.f('ix_bewerbungsunterlage_teilnehmer_id'), table_name='bewerbungsunterlage')
    op.drop_index(op.f('ix_bewerbungsunterlage_bewerbung_id'), table_name='bewerbungsunterlage')
    op.drop_table('bewerbungsunterlage')
    op.drop_index(op.f('ix_bewerbungsfreigabe_teilnehmer_id'), table_name='bewerbungsfreigabe')
    op.drop_index(op.f('ix_bewerbungsfreigabe_empfaenger_id'), table_name='bewerbungsfreigabe')
    op.drop_index(op.f('ix_bewerbungsfreigabe_bewerbung_id'), table_name='bewerbungsfreigabe')
    op.drop_table('bewerbungsfreigabe')
    op.drop_index(op.f('ix_wohlbefindenfreigabe_teilnehmer_id'), table_name='wohlbefindenfreigabe')
    op.drop_index(op.f('ix_wohlbefindenfreigabe_empfaenger_id'), table_name='wohlbefindenfreigabe')
    op.drop_table('wohlbefindenfreigabe')
    op.drop_index(op.f('ix_wohlbefindeneintrag_teilnehmer_id'), table_name='wohlbefindeneintrag')
    op.drop_index(op.f('ix_wohlbefindeneintrag_datum'), table_name='wohlbefindeneintrag')
    op.drop_table('wohlbefindeneintrag')
    op.drop_index(op.f('ix_wochenbericht_teilnehmer_id'), table_name='wochenbericht')
    op.drop_table('wochenbericht')
    op.drop_index(op.f('ix_teilnehmergruppe_handlungsfeld_id'), table_name='teilnehmergruppe')
    op.drop_table('teilnehmergruppe')
    op.drop_index(op.f('ix_psmzuordnung_teilnehmer_id'), table_name='psmzuordnung')
    op.drop_index(op.f('ix_psmzuordnung_psm_id'), table_name='psmzuordnung')
    op.drop_table('psmzuordnung')
    op.drop_index(op.f('ix_handlungsfeldmitglied_teilnehmer_id'), table_name='handlungsfeldmitglied')
    op.drop_index(op.f('ix_handlungsfeldmitglied_handlungsfeld_id'), table_name='handlungsfeldmitglied')
    op.drop_table('handlungsfeldmitglied')
    op.drop_index(op.f('ix_handlungsfeldleitung_handlungsfeld_id'), table_name='handlungsfeldleitung')
    op.drop_index(op.f('ix_handlungsfeldleitung_berufstrainer_id'), table_name='handlungsfeldleitung')
    op.drop_table('handlungsfeldleitung')
    op.drop_index(op.f('ix_board_person_teilnehmer_id'), table_name='board')
    op.drop_index(op.f('ix_board_handlungsfeld_id'), table_name='board')
    op.drop_table('board')
    op.drop_index(op.f('ix_bewerbung_teilnehmer_id'), table_name='bewerbung')
    op.drop_table('bewerbung')
    op.drop_index(op.f('ix_berufstrainerzuordnung_teilnehmer_id'), table_name='berufstrainerzuordnung')
    op.drop_index(op.f('ix_berufstrainerzuordnung_berufstrainer_id'), table_name='berufstrainerzuordnung')
    op.drop_table('berufstrainerzuordnung')
    op.drop_index(op.f('ix_auditlogeintrag_ziel_teilnehmer_id'), table_name='auditlogeintrag')
    op.drop_index(op.f('ix_auditlogeintrag_akteur_id'), table_name='auditlogeintrag')
    op.drop_table('auditlogeintrag')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_handlungsfeld_abteilung_id'), table_name='handlungsfeld')
    op.drop_table('handlungsfeld')
    op.drop_table('abteilung')
    # ### end Alembic commands ###
